### PR TITLE
Format read me

### PR DESCRIPTION
**Pull request by htwangtw**
make the landing page fitting markdown syntax

### CODE REVIEW

**Comment by htwangtw** [comment]
I am a bit surprised that this PR failed for the build :sweat_smile: 
I can have a look later...

**Comment by jameschapman19** [comment]
Weird! I'll have a look what's going on. Perhaps I haven't seeded something in there

**Comment by jameschapman19** [comment]
Got it! Basically one of those models (solving CCA by alternating least squares) is unstable so adding a small amount of regularization is important but I took it away. Will fix this now :)

**Comment by jameschapman19** [comment]
An additional problem this problem helped uncover was that some of those iterative methods were missing random seeds so not all tests were the same. This is now also being fixed!

**Comment by htwangtw** [comment]
This is awesome! Great work!

**Pull request merged**
